import Head from "next/head";
// import styles from "@/styles/Home.module.css";
import { Router, useRouter } from "next/router";
import Masa from "@/pages/masa";

import {
  Center,
  GlobalStyles,
  Title,
  Paragraph,
  Footer
} from "@/utils/theme";

export default function Home() {
  const router = useRouter();
  console.log(router.query.masa);

  if (router.query.masa) {
    return (
          <Masa masa={router.query.masa} />
    );
  } else {
    return (
      <>
        <Head>
          <title>RestoranEK</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <GlobalStyles/>
        <Center>
          <Title>RestoranEK</Title>
          <Paragraph>Lütfen masanızdaki QR kodu tekrar okutunuz.</Paragraph>
          <Footer>StudioEK</Footer>
        </Center>
      </>
    );
  }
}
