import Head from "next/head";
import { useRouter } from "next/router";
import styled from "styled-components";
import products from "@/pages/api/urunler.json";
import {
  Center,
  GlobalStyles,
  Title,
  Description,
  Ul,
  Li, Paragraph
} from "@/utils/theme";

export default function Masa({ masa }) {
  const router = useRouter();
  // console.log(router.query.masa)

  return (
    <>
      <Head>
        <title>masa {router.query.masa} - RestoranEK</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <GlobalStyles/>
          <Title>Masa</Title>
          <Description>{masa}</Description>
          <Ul>
            {products.urunler.map((product) => (
              <Li key={product.id}>
                <h1>{product.ad}</h1>
                <Paragraph>{product.description}</Paragraph>
                <Paragraph>Fiyat: {product.fiyat}₺</Paragraph>
                <Paragraph>Kategori: {product.kategori}₺</Paragraph>
              </Li>
            ))}
          </Ul>
      </Center>
    </>
  );
}
